# This workflow will upload Docker image when a release is created
# For more information see: https://github.com/marketplace/actions/docker-build-push-action

name: Publish docker image (manual)

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Version to build
      push:
        type: boolean
        description: Push to docker hub

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            pythonopenapi/openapi-spec-validator
          tags: |
            type=semver,pattern={{version}},value=${{ github.event.inputs.version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: github.event.inputs.push
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event.inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
